name: Performance Test
on:
  push:
    branches:
      - performance-test
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cypress run with env
        uses: cypress-io/github-action@v5
        env:
          PERFORMANCE_TEST: ${{ secrets.PERFORMANCE_TEST }}
        with:
          browser: chrome
          headed: true