name: Performance Test
on:
  push:
    branches:
      - performance-test
env:
  PERFORMANCE_TEST: cypress
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        run: yarn
      # - name: Build
      #   run: yarn build
      - name: Start
        run: yarn start
        wait-on: 'http://localhost:3000'
      - name: Cypress run with env
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: true
          wait-on: 'http://localhost:3000'