name: Performance Test
on:
  push:
    branches:
      - performance-test
env:
  REACT_APP_PERFORMANCE_TEST: cypress
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: performance-test
      - name: Cypress run with env
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: true
          start: yarn start
          wait-on: 'http://localhost:3000'